In [2]:
##NUMPY
import numpy as np


In [3]:
lst=[1,2,3,4]
# if we want to convert this list into an array we can do this as using numpy.

arr=np.array(lst)

In [4]:
# 1D array
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
arr1=np.array([[1,2,3],[4,5,6]])

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 2d array
arr1.shape

(2, 3)

In [10]:
# we can reshape the above 2d array using reshape function
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [12]:
# we can also change a tuple into an array
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [13]:
# we can also change dictionry into a array
di={1:"aadil",2:"hussain",3:"teeli"}

In [14]:
di

{1: 'aadil', 2: 'hussain', 3: 'teeli'}

In [15]:
result=di.items()

In [16]:
data=list(result)
arr4=np.array(data)

In [17]:
arr4

array([['1', 'aadil'],
       ['2', 'hussain'],
       ['3', 'teeli']], dtype='<U11')

In [18]:
arr4.dtype

dtype('<U11')

In [19]:
arr1.dtype

dtype('int32')

In [20]:
# we can create arrays from the scratch as :
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr6=np.arange(1,10,2)
arr6

array([1, 3, 5, 7, 9])

In [22]:
arr6.shape

(5,)

In [23]:
arr6.reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [24]:
# quickly create an array in reverse order with step size -2
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [25]:
# if we want to create an equally spaced elements to any nubmber u can use linspace() function
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [26]:
# create an array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [31]:
# we can perform mathematical operartions on the  np arrays as
5+ np.ones((3,5))   # this operation is basically known as the broadcasting operation

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [32]:
10 + np.arange(1,10,2)

array([11, 13, 15, 17, 19])

In [33]:
# creating an identity matrix there is an inbuld function eye()
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.eye(6).reshape(3,12)

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
# we can also create random numbers by using numpy as 
print("Random number generation(Uniform distribution) and the values are ranging between 0 aand 1")

np.random.rand(2,3)

Random number generation(Uniform distribution) and the values are ranging between 0 aand 1


array([[0.2390595 , 0.17747635, 0.62005883],
       [0.23388902, 0.06409669, 0.10153006]])

In [36]:
print("Random number following a normal distribution with std=1 and mean=0")
print(np.random.rand(5,3))

Random number following a normal distribution with std=1 and mean=0
[[0.57597332 0.84352852 0.99838758]
 [0.00584085 0.57138234 0.61802345]
 [0.09823657 0.33778637 0.6270958 ]
 [0.72434568 0.42826394 0.265802  ]
 [0.54788499 0.8132534  0.89176381]]


In [37]:
np.random.randint(1,100,40).reshape(4,10)

array([[73, 32, 54, 73, 76,  4, 54, 38, 18, 96],
       [75, 50, 43, 60, 31, 92, 60, 67,  3, 15],
       [ 1, 92, 37, 87, 88, 98, 90, 66,  8, 94],
       [91, 93, 60, 74, 76, 88, 33, 52, 90, 22]])

In [38]:
# create an array of 4*4 with the above random function
np.random.randint(1,100,(4,4))

array([[62, 13, 57, 62],
       [28, 69, 41, 40],
       [75, 80, 26, 11],
       [89, 67, 52, 55]])

In [39]:
# slicing
arr=np.arange(1,11)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# print all the elements after 2
arr[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# print all the elements after 5
arr[4:]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
# print the element from 4 to 8
arr[3:8]

array([4, 5, 6, 7, 8])

In [44]:
# print the last element
arr[-1]

10

In [45]:
arr[-1:7:-1]

array([10,  9])

In [46]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5])

In [48]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [49]:
arr1

array([[10, 37, 15, 70],
       [94, 46, 97, 32],
       [22,  7, 50, 91],
       [43, 82, 46, 55],
       [83, 23, 82, 82]])

In [54]:
arr1[0:3]

array([[10, 37, 15, 70],
       [94, 46, 97, 32],
       [22,  7, 50, 91]])

In [58]:
arr1[3:3]

array([], shape=(0, 4), dtype=int32)

In [62]:
arr1[0:3,0:3]

array([[10, 37, 15],
       [94, 46, 97],
       [22,  7, 50]])

In [63]:
arr1[3:,1:]

array([[82, 46, 55],
       [23, 82, 82]])

In [78]:
arr1[2:4,1:3]

array([[ 7, 50],
       [82, 46]])

In [84]:
arr1[-3:-1,-3:-1]

array([[ 7, 50],
       [82, 46]])

In [90]:
arr1[2:4,]

array([[22,  7, 50, 91],
       [43, 82, 46, 55]])

In [94]:
# select the elements as 22  91
#                        43  55


selected_elements=[
   [arr1[2][0],
   arr1[2][3]],
   [arr1[3][0],
   arr1[3][3]]

]

In [99]:
type(selected_elements)

list

In [100]:
for i in selected_elements:
    print(i)

[22, 91]
[43, 55]


In [103]:
# universal operations
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(1,100,(3,3))

In [104]:
print(arr1)
print(arr2)

[[24 45 98]
 [93 78 35]
 [59 57 81]]
[[93 84 86]
 [ 4 67 92]
 [31 94 16]]


In [105]:
# if we want to perform the mathematicle operations can we b able to this, let us check
print(arr1+arr2)

[[117 129 184]
 [ 97 145 127]
 [ 90 151  97]]


In [106]:
print(arr1/arr2)

[[ 0.25806452  0.53571429  1.13953488]
 [23.25        1.1641791   0.38043478]
 [ 1.90322581  0.60638298  5.0625    ]]


In [107]:
print(arr1*arr2)

[[2232 3780 8428]
 [ 372 5226 3220]
 [1829 5358 1296]]


In [109]:
# we can apply the various inbuild fuctions as 
print(np.sqrt(arr1))

[[4.89897949 6.70820393 9.89949494]
 [9.64365076 8.83176087 5.91607978]
 [7.68114575 7.54983444 9.        ]]


In [110]:
np.exp(arr2)

array([[2.45124554e+40, 3.02507732e+36, 2.23524660e+37],
       [5.45981500e+01, 1.25236317e+29, 9.01762841e+39],
       [2.90488497e+13, 6.66317622e+40, 8.88611052e+06]])

In [111]:
np.log10(arr1)

array([[1.38021124, 1.65321251, 1.99122608],
       [1.96848295, 1.8920946 , 1.54406804],
       [1.77085201, 1.75587486, 1.90848502]])

In [112]:
arr=np.arange(1,10)

In [113]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
arr[4:]=100   # this is called as broad casting

In [115]:
arr

array([  1,   2,   3,   4, 100, 100, 100, 100, 100])